name: VillagerCity
main: io.github.troydesante.villagercity
version: 0.0.1 - SNAPSHOT
commands:
   villagercity:
      description: VillagerCity Plugin V0.0.1 - SNAPSHOT
      usage: /<command>
      permission: villagercity.villagercity
      permission-message: Je hebt geen toestemming om dit te gebruiken!
permissions:
    villagercity.*:
        description: Geeft toegang tot alle VillagerCity commands.
    villagercity.villagercity:
        description: Geeft toegang tot de /villagercity command.